### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by ultramizer** [bharnett/Infringer#1]
Hi. 
I am running Python 3 on Mac OSX and trying to get this to work, but i always fail to run it because it can't import the modules, i have installed all of the modules using pip or easy_install, but it just doesn't find it when i try to launch infringer.py. Can you tell me why?

**Comment by ultramizer** [comment]
I managed to copy the modules to a hidden location inside OSX so that he now finds them, but he is now saying that the version of beautifulsoup is not compatible with version 3 of Python, only version 2, and i have to convert it somehow, but i have no idea how that would work...

**Comment by bharnett** [comment]
Hey, re: beautiful soup.  Try doing pip3 install beautifulsoup.  That should pull the correct version for Python 3.
